#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

#include "muse.h"

enum planck_layers { _QWERTY, _FUNCFULL, _MOVE, _SYMBOL, _TENKEY, _SPECIAL };

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[_QWERTY] = LAYOUT_planck_1x2uC(
// Qwerty
//  ,--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------.
       KC_ESC,    KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P, KC_MINS,
//  |--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|
      KC_LCTL,    KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L, KC_SCLN, KC_QUOT,
//  |--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|
      KC_LSFT,    KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M, KC_COMM,  KC_DOT, KC_SLSH, KC_BSLS,
//  |--------|--------|--------|--------|--------|-----------------|--------|--------|--------|--------|--------|
     MO(4),KC_LGUI,KC_LALT,LT(3,KC_LANG2),LT(1,KC_TAB),LSFT_T(KC_SPC),LT(2,KC_ENT),KC_RCTL,KC_RALT,KC_APP,KC_LANG1),
//  `--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------'

	[_FUNCFULL] = LAYOUT_planck_1x2uC(
// Functions and Full key
//  ,--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------.
      KC_TILD, KC_EXLM,   KC_AT, KC_HASH,  KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_PLUS,
//  |--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|
       KC_GRV,    KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,  KC_EQL,
//  |--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|
        KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,  KC_F10,   KC_F11, KC_F12,
//  |--------|--------|--------|--------|--------|-----------------|--------|--------|--------|--------|--------|
      KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,          KC_TRNS,   MO(5), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
//  `--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------'

	[_MOVE] = LAYOUT_planck_1x2uC(
// Cursor and page transition
//  ,--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------.
       KC_ESC,   KC_NO,   KC_NO,   KC_NO,   KC_NO,  KC_NO,KC_PGUP,RSFT(KC_TAB),KC_TAB, KC_PGDN, KC_RCTL, KC_BSPC,
//  |--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|
      KC_TRNS,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO, KC_LEFT, KC_DOWN,   KC_UP, KC_RGHT,  KC_ESC, KC_RALT,
//  |--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|
      KC_TRNS,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,  KC_DEL, KC_HOME,  KC_END, KC_BSPC, KC_RSFT,   KC_NO,
//  |--------|--------|--------|--------|--------|-----------------|--------|--------|--------|--------|--------|
      KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,   MO(5),          KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
//  `--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------'

// Structural symbols
	[_SYMBOL] = LAYOUT_planck_1x2uC(
//  ,--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------.
       KC_ESC,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,  KC_GRV, KC_QUOT, KC_DQUO,   KC_NO, KC_BSPC,
//  |--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|
      KC_TRNS,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO, KC_LBRC, KC_LCBR, KC_RCBR, KC_RBRC,   KC_NO,
//  |--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|
      KC_TRNS,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO, KC_LPRN,   KC_LT,   KC_GT, KC_RPRN,   KC_NO,
//  |--------|--------|--------|--------|--------|-----------------|--------|--------|--------|--------|--------|
      KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,          KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
//  `--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------'

// Ten key
	[_TENKEY] = LAYOUT_planck_1x2uC(
//  ,--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------.
      KC_TRNS,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO, KC_PSLS,   KC_P7,   KC_P8,   KC_P9, KC_PAST, KC_BSPC,
//  |--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|
      KC_TRNS,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO, KC_PMNS,   KC_P4,   KC_P5,   KC_P6, KC_PPLS,   KC_NO,
//  |--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|
      KC_TRNS,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO, KC_NLCK,   KC_P1,   KC_P2,   KC_P3, KC_PEQL,   KC_NO,
//  |--------|--------|--------|--------|--------|-----------------|--------|--------|--------|--------|--------|
      KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,          KC_TRNS,   KC_P0, KC_PCMM, KC_PDOT, KC_PENT,   KC_NO),
//  `--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------'

	[_SPECIAL] = LAYOUT_planck_1x2uC(
// Special controls
//  ,--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------.
        RESET,   DEBUG,   KC_NO, KC_BRID, KC_BRIU,   KC_NO, KC_MUTE, KC_VOLD, KC_VOLU,   KC_NO,   KC_NO,  MU_OFF,
//  |--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|
      KC_CAPS, BL_TOGG, BL_BRTG,RGB_RMOD, RGB_MOD, RGB_TOG, RGB_SAD, RGB_HUD, RGB_HUI, RGB_SAI,  MU_MOD, KC_NLCK,
//  |--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|
      KC_TRNS, BL_STEP,  BL_OFF,  BL_DEC,  BL_INC,   BL_ON, RGB_SPD, RGB_VAD, RGB_VAI, RGB_SPI,  MUV_DE,  MUV_IN,
//  |--------|--------|--------|--------|--------|-----------------|--------|--------|--------|--------|--------|
      LCG_SWP, LCG_NRM,   KC_NO,   KC_NO, KC_TRNS,          RGB_SAD, KC_TRNS,   KC_NO,   KC_NO,   KC_NO,   MU_ON)
//  `--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------+--------'
};


